### ISSUE TITLE
Problems when using with Asp.net 5

### ISSUE THREAD

**Issue by JSinghDev** [HeadspringLabs/Enumeration#21]
The Nuget package does not work with ASP.net 5 projects. 
There is an issue with dependencies when used with .net core as the Serializable Attribute is not available in .net core 5

**Comment by plioi** [comment]
This discussion suggests that in general, you can just drop [Serializable] and add [DataContract] and [DataMember]: http://stackoverflow.com/questions/12903262/portable-class-library-recommended-replacement-for-serializable

However, I don't think that helps in the case of the members of *child* classes of `Enumeration`, so that alone would probably be a breaking change.

The discussion in that same thread about how JSON.NET deals with [Serializable] might be a more realistic answer for us, but I'm far less familiar with that concept.

**Comment by plioi** [comment]
Closing due to age.
