### ISSUE TITLE
Add support for .NET Standard

### ISSUE THREAD

**Issue by Nbjohnston86** [HeadspringLabs/Enumeration#28]
Hello! I found this package, and it solves a very real problem for me. I was trying to use it in my project, but I'm using .NET 5, and this package/library still uses .NET Framework.

Is it possible to update this to also support .NET Standard so it could be used in both?

**Comment by plioi** [comment]
The NuGet package, in addition to the problem you describe, was an older style of package for which there was no dll referenced. Instead, it would just place the single code file into your solution. I don't believe modern `dotnet pack` handles that as a first class concept anymore.

So, rather than waiting on such an adjustment, your best bet is to include Enumeration.cs directly into your solution from here: https://github.com/HeadspringLabs/Enumeration/blob/master/Enumeration.cs

**Comment by Nbjohnston86** [comment]
Oh, I had no idea that it worked that way. I could copy the file, I'm just worried about crediting/licensing/referencing where I got it from. I see that this is MIT licensed, does that mean I can just use it without worrying about it? That was why I was trying to use it as a nuget package, referencing rather than just copying it, to avoid such issues. I'm just trying to do this as close to "the right way" as possible, especially since I want to upload the project I'm working on to github eventually. Thanks for any clarification!

**Comment by plioi** [comment]
Oh, I appreciate that concern. For due diligence, then, I suggest imitating the full impact of what the nuspec would have applied to an older project:

https://github.com/HeadspringLabs/Enumeration/blob/master/Enumeration.nuspec#L19-L20

A folder dedicated to the code file that would be copied into your solution, with the license file right beside it.

**Comment by Nbjohnston86** [comment]
I will do exactly that then. Thank you again!

**Comment by mahendramavani** [comment]
It's single file codebase. Just inline it in your code and it will work for
any version you want to use

**Comment by Atulin** [comment]
@Nbjohnston86 MIT means, more or less, "you can do whatever as long as you don't hold the author accountable and place the MIT license somewhere". There will be no problem just taking the code and using it.
